### ISSUE TITLE
ContinuousData not accessible via download

### ISSUE THREAD

**Issue by heather-steckley** [dbeaudoinfortin/NAPSDataAnalysis#25]
**Issue:**
Issue accessing the zipped folders within ContinuousData

**Details:**
In trying to download and view the zipped folders of .csv files in ContinuousData, I run into an issue saying that Windows cannot open the folder (see screenshot below). This happened both when trying to download individual zipped folders within ContinuousData and when I downloaded all files within the repository. This issue did not occur, however, when accessing the IntegratedData folder contents

**Screenshot:**
![image](https://github.com/user-attachments/assets/21898492-fff7-4d9d-a7a1-aed031a1ba6e)

**Environment:**
 - OS: Windows 11 Enterprise

**Comment by dbeaudoinfortin** [comment]
Hi @heather-steckley!

I'm really happy you are looking at my repo.

The datasets are very big, even when compressed. GitHub imposes a maximum file size of 100MB for regular files. Anything bigger requires the use of Git LFS (large file storage). This would require you to download the files using a Git client.

To get around this problem, I just re-uploaded the exports as multi-part zip files. Each part is now within the GitHub limit of 100MB. If you download all of the parts, Windows will automatically recognize it as one single zip file. You can find these here:

- https://github.com/dbeaudoinfortin/NAPSDataAnalysis/tree/main/exports/ContinuousData/PerPollutant/Multipart
- https://github.com/dbeaudoinfortin/NAPSDataAnalysis/tree/main/exports/ContinuousData/PerSite/Multipart
- https://github.com/dbeaudoinfortin/NAPSDataAnalysis/tree/main/exports/ContinuousData/PerYear/Multipart

If you are interested in just a single pollutant, I have added multipart exports [here](https://github.com/dbeaudoinfortin/NAPSDataAnalysis/tree/main/exports/ContinuousData/PerPollutant/Individual%20Pollutants).

One more thing to keep in mind is that Excel may not be able to open some of these exports that are larger than 2GB. In that case, you may want to look at the per-site exports and open just one site at a time.

Let me know if this data can help you. I have spent many hours writing individual parsers for each of the many different data formats of the NAPS. I have spent a lot of time fixing mistakes and data format inconsistencies.

**Comment by heather-steckley** [comment]
Thanks so much @dbeaudoinfortin, I'm able to access the ContinuousData now! 

This data is very helpful, and I can appreciate the amount of work that went in to parsing out the NAPS data in its many formats, so thank you again!

**Comment by dbeaudoinfortin** [comment]
@heather-steckley, I just want to let you know that I have created a simple web page with some dropdowns that makes it easy to download the NAPS data: https://dbeaudoinfortin.github.io/NAPSDataAnalysis/

If there are other tools that could be helpful to you, please let me know. Thanks!

**Comment by heather-steckley** [comment]
Thanks @dbeaudoinfortin for the update and for sharing the download webpage! I can't think of any other specific tools that would be useful for our purposes at this point, but if I do, I will let you know. Thanks again!
